- op: replace
  path: /info
  value:
    title: Ory Kratos API
    description: |
      Documentation for all public and administrative Ory Kratos APIs. Public and administrative APIs
      are exposed on different ports. Public APIs can face the public internet without any protection
      while administrative APIs should never be exposed without prior authorization. To protect
      the administative API port you should use something like Nginx, Ory Oathkeeper, or any other
      technology capable of authorizing incoming requests.
    version: >-
      {{ getenv "CIRCLE_TAG" }}
    license:
      name: Apache 2.0
    contact:
      email: "hi@ory.sh"

- op: replace
  path: /servers
  value:
    - url: https://{tenant}.tenants.oryapis.com/api/kratos/{api}
      variables:
        tenant:
          default: demo
          description: Tenant ID as provided by Ory Cloud.
        api:
          default: public
          description: Target the public or administrative API.
          enum:
            - public
            - admin

- op: replace
  path: /components/securitySchemes/sessionCookie
  value:
    type: apiKey
    in: cookie
    name: ory_kratos_session

- op: replace
  path: /tags
  value:
    - name: admin
      description: All administrative API endpoints exposed at the admin API port.
      externalDocs:
        url: https://www.ory.sh/kratos/docs/reference/api
    - name: public
      description: All public API endpoints exposed at the public API port.
      externalDocs:
        url: https://www.ory.sh/kratos/docs/reference/api
